name: 'Fetch Org Repos'
description: 'Fetch all repositories in a GitHub organization'
inputs:
  organization:
    description: 'The name of the organization'
    required: true
  github_token:
    description: 'GitHub Token for authentication'
    required: true
outputs:
  repositories:
    description: 'Array of repository names in the organization'

runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install
      working-directory: ./scripts

    - name: Fetch repos and set output
      id: fetch_repos
      run: |
        node fetch-repos.js ${{ inputs.organization }} ${{ inputs.github_token }}
      working-directory: ./scripts

    - name: Set repositories output
      run: echo "::set-output name=repositories::$(cat ./scripts/repo-output.txt)"
